sources:
  - name: wk1_tf_dataset
    description: >
      This dataset contains raw trip records for yellow taxis, green taxis, and for-hire vehicles (FHVs) in New York City. 
      Each source table corresponds to a different mode of transportation and includes various attributes such as pickup and dropoff times, locations, fare amounts, and more.
    database: dlt-bigquery-484316
    schema: wk1_tf_dataset
    tables:
      - name: fhv_tripdata
        description: Raw for-hire vehicle (FHV) trip records
        config:
          loaded_at_field: pickup_datetime
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
        columns:
          - name: dispatching_base_num
            description: The unique identifier for the FHV base that dispatched the trip
          - name: pickup_datetime
            description: The date and time when the trip started
          - name: dropOff_datetime
            description: The date and time when the trip ended
          - name: PUlocationID
            description: The location ID where the trip started
          - name: DOlocationID
            description: The location ID where the trip ended 
          - name: SR_Flag
            description: The shared ride flag
          - name: Affiliated_base_number
            description: The unique identifier for the FHV base affiliated with the trip

      - name: green_tripdata
        description: Raw green taxi trip records
        config:
          loaded_at_field: lpep_pickup_datetime
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
        columns:
          - name: VendorID
            description: A code indicating the provider associated with the trip record
          - name: lpep_pickup_datetime
            description: The date and time when the trip started
          - name: lpep_dropoff_datetime
            description: The date and time when the trip ended
          - name: Store_and_fwd_flag
            description: This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, 'Y' = store and forward; 'N' = not a store and forward trip
          - name: RatecodeID
            description: The final rate code in effect at the end of the trip
          - name: PULocationID
            description: The location ID where the trip started
          - name: DOLocationID
            description: The location ID where the trip ended
          - name: passenger_count
            description: The number of passengers in the vehicle (driver entered value)
          - name: trip_distance
            description: The elapsed trip distance in miles reported by the taximeter 
          - name: fare_amount
            description: The time-and-distance fare calculated by the meter
          - name: extra
            description: Miscellaneous extras and surcharges. Currently, this only includes the $0.50 MTA tax
          - name: mta_tax
            description: $0.50 MTA tax that is automatically triggered based on the flag indicated above
          - name: tip_amount
            description: Tip amount. This field is automatically populated for credit card tips. Cash tips are not included
          - name: tolls_amount
            description: Total amount of all tolls paid in trip
          - name: ehail_fee
            description: The amount paid for an e-hail transaction. This is automatically populated for e-hail trips, but not for street hail trips 
          - name: improvement_surcharge
            description: $0.30 improvement surcharge that is automatically triggered based on the flag indicated above
          - name: total_amount
            description: The total amount charged to passengers. Does not include cash tips
          - name: payment_type
            description: A numeric code signifying how the passenger paid for the trip
          - name: trip_type
            description: A code indicating whether the trip was a street-hail trip (1) or a dispatched trip (2)
          - name: congestion_surcharge
            description: $2.50 congestion surcharge that is automatically triggered based on the flag indicated above
          

      - name: yellow_tripdata
        description: Raw yellow taxi trip records
        config:
          loaded_at_field: tpep_pickup_datetime
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
        columns:
          - name: VendorID
            description: A code indicating the provider associated with the trip record
          - name: tpep_pickup_datetime
            description: The date and time when the trip started
          - name: tpep_dropoff_datetime
            description: The date and time when the trip ended
          - name: passenger_count
            description: The number of passengers in the vehicle (driver entered value)
          - name: trip_distance
            description: The elapsed trip distance in miles reported by the taximeter
          - name: RatecodeID
            description: The final rate code in effect at the end of the trip
          - name: store_and_fwd_flag
            description: This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, 'Y' = store and forward; 'N' = not a store and forward trip
          - name: PULocationID
            description: The location ID where the trip started
          - name: DOLocationID
            description: The location ID where the trip ended
          - name: payment_type
            description: A numeric code signifying how the passenger paid for the trip
          - name: fare_amount
            description: The time-and-distance fare calculated by the meter
          - name: extra
            description: Miscellaneous extras and surcharges. Currently, this only includes the $0.50 MTA tax
          - name: mta_tax
            description: $0.50 MTA tax that is automatically triggered based on the flag indicated above
          - name: tip_amount
            description: Tip amount. This field is automatically populated for credit card tips. Cash tips are not included
          - name: tolls_amount
            description: Total amount of all tolls paid in trip
          - name: improvement_surcharge
            description: $0.30 improvement surcharge that is automatically triggered based on the flag indicated above
          - name: total_amount
            description: The total amount charged to passengers. Does not include cash tips
          - name: congestion_surcharge
            description: $2.50 congestion surcharge that is automatically triggered based on the flag indicated above   
          - name: airport_fee
            description: $1.00 airport fee that is automatically triggered based on the flag indicated above
